### ISSUE TITLE
SVG the logo

### ISSUE THREAD

**Issue by lennybacon** [MobilesWuppertal/WebSite#2]
It would be great to have the logo as SVG.

**Comment by akamola** [comment]
Attached you can find the logo of *Mobiles Wuppertal* as SVG. I've exported two versions: one with and one without the word mark.

Note: The gradient was exported as Base64 encoded bitmap into the SVG, what makes them quite big (about 920 KB each).

![mobiles-wuppertal_logo_wordmark](https://github.com/MobilesWuppertal/WebSite/assets/368349/83667c7e-a2ba-4019-908d-947c8852448b)
![mobiles-wuppertal_logo](https://github.com/MobilesWuppertal/WebSite/assets/368349/d294696b-5f39-4846-93af-88495c6a589a)

**Comment by lennybacon** [comment]
Sorry to say but this is a jpeg embedded in SVG...

![image](https://github.com/MobilesWuppertal/WebSite/assets/272164/0249b350-2b2d-44c6-917e-86d6c9f79e57)

**Comment by lennybacon** [comment]
I'll go with this if no one stops me...

```xml
<svg height="400" width="550" xmlns="http://www.w3.org/2000/svg">
  <defs>
	<radialGradient id="grad1" gradientTransform="translate(-0.87 -0.14) scale(2, 2)">
      <stop offset="0%" stop-color="#47f504"/>
      <stop offset="25%" stop-color="#47f504"/>
      <stop offset="50%" stop-color="#ff2170"/>
      <stop offset="74%" stop-color="#ff2170"/>
      <stop offset="100%" stop-color="#ff81f1"/>
    </radialGradient>
  </defs>
  <path d="M 163 44 C 184 24 196 22 214 22 C 238 22 262 30 271 67 C 303 38 338 26 371 26 C 453 26 513 92 513 169 C 513 251 445 310 370 310 C 335 310 294 295 263 260 L 226 362 L 177 362 L 149 283 L 120 362 L 72 362 L 25 218 L 75 218 L 97 306 L 99 306 L 124 218 L 174 218 L 202 307 L 223 218 L 286 218 C 308 255 343 267 372 267 C 425 267 471 222 471 168 C 471 113 424 69 371 69 C 323 69 273 105 273 168 L 223 168 L 223 87 C 221 73 212 63 199 63 C 175 63 173 88 173 100 L 173 168 L 124 168 L 124 85 C 119 71 114 63 101 63 C 83 63 74 79 74 93 L 74 168 L 25 168 L 25 24 L 72 24 C 72 29 72 34 73 39 C 89 23 101 22 116 22 C 131 22 149 24 163 44 Z" fill="url(#grad1)" />
</svg>
```

Here is a preview: https://jsfiddle.net/lennybacon/cnufypg6/

![image](https://github.com/MobilesWuppertal/WebSite/assets/272164/01c614a2-7694-4276-8cf8-5ae17b8a2b09)


It is 1,048 bytes in size

**Comment by akamola** [comment]
Yeah, go with your SVG recreation. As said in the email: I think we'll need to adjust the colors, but this is an easy task in the SVG we can stale a offset a bit from now.
